sudo: required
dist: bionic

language: python

cache:
  bundler: true
  pip: true

python:
  - "3.4"

virtualenv:
  system_site_packages: true

before_install: 
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-pyqtgraph python3-pyqt5 python3-pyserial pyqt5-dev-tools

install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - make

script:
  - nosetests




