sudo: required
dist: bionic

language: python

cache:
  bundler: true
  pip: true

python:
  - "3.4"

before_install: 
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-pyqtgraph python3-pyqt5 python3-serial pyqt5-dev-tools

install:
    - make clean
    - make

script:
  - nosetests




