site_name: KuttyPy Graphical Interface Documentation
theme: 'material'

#theme: 'readthedocs'
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - smarty
    - wikilinks
    - codehilite:
        linenums: False
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
       preserve_tabs: true
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.tilde

extra_css: ["assets/main.css"]

extra:
  favicon: 'images/kuttypy.png'
  logo: 'images/kuttypy.png'
  palette:
      primary: '#087da1'
      accent: '#00a889'
  social:
    - type: 'github'
      link: 'https://github.com/csparkresearch/'
    - type: 'twitter'
      link: 'https://twitter.com/csparkresearch'


repo_name: 'csparkresearch/kuttypy-gui'
repo_url: 'https://github.com/csparkresearch/kuttypy-gui'
copyright: 'Copyright © 2019 <a href="https://csparkresearch.in">CSpark Research</a>'
#google_analytics:
#  - 'UA-49052879-1'
#  - 'auto'
nav:
  - Home: 'index.md'
  - Installation:
      - 'Getting started': 'installation/gettingstarted.md'
  - I2C Sensors:
      - 'Introduction': 'sensors.md'
  - Other features:
      - '8 Channel Voltmeter': 'adc.md'
      - 'Stepper Motors': 'stepper.md'
  - Python Programming:
      - 'Introduction': 'programming/intro.md'
      - 'Basic I/O': 'programming/basics.md'
      - 'I2C and Sensors': 'programming/i2c.md'
  - C Programming:
      - 'Introduction': 'programming/c.md'

