site_name: KuttyPy Graphical Interface Documentation
theme: 'material'


#theme: 'readthedocs'
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - smarty
    - wikilinks
    - codehilite:
        linenums: False
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
       preserve_tabs: true
       custom_fences: 
         - name: flow
           class: uml-flowchart
           format: !!python/name:pymdownx.superfences.fence_code_format
         - name: sequence
           class: uml-sequence-diagram
           format: !!python/name:pymdownx.superfences.fence_code_format
         - name: math
           class: arithmatex
           format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.tilde

extra_css: ["assets/main.css"]


site_favicon: 'images/favicon.ico'


extra:
  palette:
      primary: '#087da1'
      accent: '#00a889'
  logo: 'images/kuttypy.png'
  social:
    - type: 'github'
      link: 'https://github.com/csparkresearch/'
    - type: 'twitter'
      link: 'https://twitter.com/csparkresearch'

repo_name: 'csparkresearch/kuttypy-gui'
repo_url: 'https://github.com/csparkresearch/kuttypy-gui'
copyright: 'Copyright © 2017 <a href="https://csparkresearch.in">CSpark Research</a>'
#google_analytics:
#  - 'UA-49052879-1'
#  - 'auto'
pages:
  - Home: 'index.md'
  - Installation:
      - 'Getting started': 'installation/gettingstarted.md'
  - I2C Sensors:
      - 'Introduction': 'sensors.md'
  - Programming:
      - 'Introduction': 'programming/intro.md'
      - 'Basic I/O': 'programming/basics.md'
      - 'I2C and Sensors': 'programming/i2c.md'
